name: Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, rust-docs

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            lorawan -> target
          cache-directories: |
            lorawan/target/doc

      - name: Build documentation
        working-directory: ./lorawan
        run: |
          # Verify we're in the right directory
          test -f Cargo.toml || (echo "Cargo.toml not found" && exit 1)
          
          # Build docs
          cargo doc --no-deps --all-features
          
          # Create redirect
          echo '<meta http-equiv="refresh" content="0; url=lorawan">' > target/doc/index.html
          
          # Ensure .nojekyll exists
          touch target/doc/.nojekyll

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: lorawan/target/doc
          clean: true